routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('restaurants', 'RestaurantController');

app/Day.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Restaurant;
use App\Hour;

class Day extends Model
{
    public function restaurants() {
        return $this->belongsToMany(Restaurant::class, Hour::class)->withPivot('id', 'start', 'end');
    }
}

app/Hour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Hour extends Model
{
    use SoftDeletes;

    protected $table = 'hours';

    protected $fillable = ['restaurant_id', 'day_id', 'start', 'end'];
}

app/Restaurant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Day;
use App\Hour;

class Restaurant extends Model
{
    use SoftDeletes;

    protected $table = 'restaurants';

    protected $fillable = ['name'];

    public function days() {
        return $this->belongsToMany(Day::class, Hour::class)->withPivot('start', 'end');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/RestaurantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Restaurant;
use Illuminate\Support\Facades\Log;
use App\Day;

class RestaurantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $restaurants = Restaurant::with('days')->get();
        return view('restaurants.index')->with(['restaurants' => $restaurants]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $days = Day::all();
        return view('restaurants.create')->with(['days' => $days]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $starts = $request->all()['start'];
        $ends = $request->all()['end'];
        $restaurant = new Restaurant();
        $restaurant->name = $request->input('name');
        $restaurant->save();
        foreach ($starts as $key => $array){
          foreach ($array as $k => $value) {
            if($value && $ends[$key][$k]) {
                $restaurant->days()->attach([$key => ['start' => $value, 'end' => $ends[$key][$k]]]);
            }
          }
        }
        return redirect('restaurants/'.$restaurant->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $restaurant = Restaurant::find($id);
        $days = Day::with(['restaurants' => function ($query) use($id) {
            $query->where('restaurants.id', $id);
        }])->get();
        return view('restaurants.show')->with([
            'restaurant' => $restaurant,
            'days' => $days
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $days = Day::with(['restaurants' => function ($query) use($id) {
            $query->where('restaurants.id', $id);
        }])->get();
        $restaurant = Restaurant::find($id);
        return view('restaurants.edit', compact('days','restaurant'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $starts = $request->all()['start'];
        $ends = $request->all()['end'];
        $restaurant = Restaurant::find($id);
        $restaurant->name = $request->input('name');
        $restaurant->save();
        $restaurant->days()->detach();
        foreach ($starts as $key => $array){
          foreach ($array as $k => $value) {
            if($value && $ends[$key][$k]) {
                $restaurant->days()->attach([$key => ['start' => $value, 'end' => $ends[$key][$k]]]);
            }
          }
        }
        return redirect('restaurants/'.$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Restaurant::destroy($id);
        return redirect('restaurants/');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
</body>
</html>

resources/views/restaurants/create.blade.php
<div class="container">
    <div class="row justify-content-center">
        <form method="post" action="{{ route('restaurants.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Nom du restaurant :</label>
                <input type="text" class="form-control" name="name" required/>
            </div>
            @foreach ($days as $day)
                <p>{{$day->name}}</p>
                <button type="button" class="addDay" day="{{$day->id}}">Ajouter un horaire le {{$day->name}}</button>
                <div id="day{{$day->id}}">
                    <div class="form-group">
                        <label>Horaire d'ouverture: </label>
                        <input type="time" name="start[{{$day->id}}][]">
                        <label>Horaire de fermeture</label>
                        <input type="time" name="end[{{$day->id}}][]">
                    </div>
                </div>
            @endforeach
            <button type="submit" class="btn btn-primary">Créer le restaurant</button>
        </form>
    </div>
</div>
<script>
    Array.from(document.getElementsByClassName('addDay')).forEach(function(element) {
       element.addEventListener('click', function(elem) {
            console.log('click')
            const dayId = elem.target.getAttribute('day');
            const targetDiv = document.getElementById('day' + dayId);
            const newDay = '<div class="form-group"><label>Horaire d\'ouverture: </label><input type="time" name="start['+ dayId +'][]"><label>Horaire de fermeture</label><input type="time" name="end['+ dayId +'][]"></div>';
            targetDiv.innerHTML += newDay
       });
     });
 </script>

resources/views/restaurants/edit.blade.php
<form method="post" action="{{ route('restaurants.update', $restaurant->id) }}">
    @csrf
    {{ method_field('PATCH') }}
    <div class="form-group">
        <input type="text" name="name" value="{{$restaurant->name}}" required>
    </div>
    @foreach($days as $day)
        <strong>{{ $day->name }} :</strong><br>
        <button type="button" class="addDay" day="{{$day->id}}">+</button>
        <div id="day{{$day->id}}">
            @foreach($day->restaurants as $restaurant)
              <div class="form-group">
              <input type="time"  name="start[{{$day->id}}][]" value="{{$restaurant->pivot->start}}">
                  <input type="time" name="end[{{$day->id}}][]" value="{{$restaurant->pivot->end}}">
                  <li>{{ $restaurant->pivot->start }} à {{ $restaurant->pivot->end ?? null }}</li>
              </div>
            @endforeach
        </div>
    @endforeach
    <button type="submit" class="btn btn-primary">Modifier le restaurant</button>
        </form>
        <script>
           Array.from(document.getElementsByClassName('addDay')).forEach(function(element) {
              element.addEventListener('click', function(elem) {
                const dayId = elem.target.getAttribute('day');
                const targetDiv = document.getElementById('day' + dayId);
                const newDay = '<div class="form-group"><input type="time" name="start['+ dayId +'][]"><input type="time" name="end['+ dayId +'][]"></div>';
                targetDiv.innerHTML += newDay
              });
            });
        </script>

resources/views/restaurants/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @if($restaurants)
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nom du restaurant</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach($restaurants as $restaurant)
                    <tr>
                        <th scope="col">{{$restaurant->name}}</th>
                            <td scope="col">
                                <div class='btn-group'>
                                    <a href="{{ route('restaurants.show', [$restaurant->id]) }}" class='btn btn-default btn-xs'>Voir les horaires</a>
                                    @auth
                                    <a href="{{ route('restaurants.edit', [$restaurant->id]) }}" class='btn btn-default btn-xs'>Editer</a>
                                    {!! Form::open(['route' => ['restaurants.destroy', $restaurant->id], 'method' => 'delete']) !!}
                                    {!! Form::button('Supprimer', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Voulez-vous supprimer le restaurant ?')"]) !!}
                                    {!! Form::close() !!}
                                    @endauth
                                </div>
                            </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        @else
        Pas de restaurants sur l'application @auth <a href="{{ route('restaurants.create') }}" class='btn btn-default btn-xs'>Créer un restaurant</a> @endauth
        @endif
    </div>
</div>
@endsection

resources/views/restaurants/show.blade.php
<h2>{{$restaurant->name}}</h2>
<h3>Horaires d'ouverture :</h3>
    <div class="row">

        @foreach($days as $day)
        <strong>{{ $day->name }} :</strong><br>
            @if($day->restaurants->count() > 0)
                <ul>
                @foreach($day->restaurants as $restaurant)
                    <li>{{ $restaurant->pivot->start }} à {{ $restaurant->pivot->end }}</li>
                @endforeach
                </ul>
            @else
            <div class="row">
                Fermé
            </div>
            @endif
        @endforeach
    </div>